include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore   # freezed + json_serializable
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint          # habilita riverpod_lint

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - unawaited_futures
    - use_key_in_widget_constructors
    - directives_ordering
    - require_trailing_commas
